sudo: false

language: java

jdk:
  - oraclejdk8

deploy:
  provider: s3
  access_key_id: AKIAYRXK3BZDIREVCIG4
  secret_access_key:
    secure: ORE56kC7viikGMGRg7szKjWysjsxlT3hEp0PjSackWzOIG/uCleN/P57wDns5wE5Y/ROGOlCAFBR/+jcDN2apiShhkW/mMYarFORsD6dsJNv2x7y9eSCIOV35VjrdxjbUPoipDjhlWeH2G4qEEH1pKmKR51HLonWYYB/F9B3FPw=
  bucket: languagetool-builds
